### PR TITLE
Ensure timeout is set on new sockets.

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes mozilla-services/vaurien#51 and mozilla-services/vaurien#52

### CODE REVIEW

**Comment by lukebakken** [comment]
Hm, needs more work, getting a different error in a TCP scenario:

```
Traceback (most recent call last):
  File "/home/lbakken/Projects/src/vaurien/lib/python2.7/site-packages/gevent-1.1.0-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/lbakken/Projects/src/vaurien/lib/python2.7/site-packages/gevent-1.1.0-py2.7-linux-x86_64.egg/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/lbakken/Projects/src/vaurien/vaurien/proxy.py", line 123, in handle
    res = [green.get() for green in greens]
  File "/home/lbakken/Projects/src/vaurien/lib/python2.7/site-packages/gevent-1.1.0-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 480, in get
    self._raise_exception()
  File "/home/lbakken/Projects/src/vaurien/lib/python2.7/site-packages/gevent-1.1.0-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 171, in _raise_exception
    reraise(*self.exc_info)
  File "/home/lbakken/Projects/src/vaurien/lib/python2.7/site-packages/gevent-1.1.0-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/lbakken/Projects/src/vaurien/vaurien/proxy.py", line 221, in _weirdify
    behavior, behavior_name)
  File "/home/lbakken/Projects/src/vaurien/vaurien/proxy.py", line 169, in _weirdify
    return self.handler(source, dest, to_backend, behavior)
  File "/home/lbakken/Projects/src/vaurien/vaurien/protocols/base.py", line 59, in __call__
    lambda: behavior.on_between_handle(self, source,
  File "/home/lbakken/Projects/src/vaurien/vaurien/protocols/tcp.py", line 34, in _handle
    data = self._get_data(dest)
  File "/home/lbakken/Projects/src/vaurien/vaurien/protocols/base.py", line 52, in _get_data
    return get_data(sock, buffer)
  File "/home/lbakken/Projects/src/vaurien/vaurien/util.py", line 189, in get_data
    return sock.recv(buffer)
  File "/home/lbakken/Projects/src/vaurien/lib/python2.7/site-packages/gevent-1.1.0-py2.7-linux-x86_64.egg/gevent/_socket2.py", line 280, in recv
    self._wait(self._read_event)
  File "/home/lbakken/Projects/src/vaurien/lib/python2.7/site-packages/gevent-1.1.0-py2.7-linux-x86_64.egg/gevent/_socket2.py", line 179, in _wait
    self.hub.wait(watcher)
  File "/home/lbakken/Projects/src/vaurien/lib/python2.7/site-packages/gevent-1.1.0-py2.7-linux-x86_64.egg/gevent/hub.py", line 627, in wait
    result = waiter.get()
  File "/home/lbakken/Projects/src/vaurien/lib/python2.7/site-packages/gevent-1.1.0-py2.7-linux-x86_64.egg/gevent/hub.py", line 875, in get
    return self.hub.switch()
  File "/home/lbakken/Projects/src/vaurien/lib/python2.7/site-packages/gevent-1.1.0-py2.7-linux-x86_64.egg/gevent/hub.py", line 606, in switch
    return greenlet.switch(self)
timeout: timed out
```

**Comment by lukebakken** [comment]
https://github.com/benoitc/gunicorn/issues/880

https://bitbucket.org/eventlet/eventlet/issues/143/socket-timeouts-in-wsgi-server-not-caught

**Comment by lukebakken** [comment]
The `greenlet.switch` exception was resolved by using the `--protocol-tcp-keep-alive` option. It does seem necessary to add the `conn.settimeout(self.timeout)` call in `proxy.py`

**Comment by bchess** [comment]
Bump.. so is this able to be merged?

**Comment by andrewmichaelsmith** [comment]
Just giving this a further bump - hit this today, as far as I can tell the latest version (1.9) and previous version (1.8) on pypi are totally unusable. 

Can confirm that running @lukebakken fixed the issue for me.

**Comment by tarekziade** [comment]
Thanks

**Pull request merged**
